- name: installing apache
  hosts: web
  user : root
  become: yes

  tasks:
  - name: Ensure httpd package is present
    yum:
      name: httpd
      state: latest

  - name: Ensure httpd is started
    service:
      name: httpd
      state: started
